---
- name: Save Network Config to Persistent AWX Directory
  hosts: all
  gather_facts: no # Keep this as 'no'
  
  vars:
    # Use the lookup plugin to get the current timestamp from the AWX host
    current_timestamp: "{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"
    
  tasks:
    - name: Get and save running config
      cisco.ios.ios_config:
        backup: yes
        backup_options:
          # Use the new variable 'current_timestamp' for the folder name
          dir_path: "/var/lib/awx/projects/network_backups/{{ current_timestamp }}"
          filename: "{{ inventory_hostname }}_config.cfg"