---
- name: save Network Config to Persistent AWX Directory
  hosts: all
  become: yes
  gather_facts: yes
  
  tasks:
    - name: get and save running config
      cisco.ios.ios_config:
        backup: yes
        backup_options:
          # Define the absolute, persistent path inside the container.
          dir_path: "/var/lib/awx/projects/network_backups/{{ ansible_date_time.iso8601 | regex_replace('[^0-9]', '_') }}"
          
          # Optional: Define the filename format
          filename: "{{ inventory_hostname }}_config.cfg"
      
