---
# secret key is ojdT9y5319YnWbGHVnAb2EkkAM8ou0
all: # you need to use all: 
  children: # you use children to denote subgroups
    petrovci:
      children: 
        routers:
          hosts:
            192.168.206.5: # <-- Key is the host address
            172.16.0.2:    # <-- Value is an empty dictionary (optional host vars would go here)
            172.16.0.6:
          vars:
            testVar: 999
        switches: 
          hosts:
            192.168.99.1:
            192.168.99.2:
      vars: 
        ansible_connection: network_cli
        ansible_network_os: ios
        ansible_user: admin
        ansible_ssh_pass: Cisco123
        ansible_become_password: Cisco123